"""rate_limited

Revision ID: 0c3414079bfe
Revises: 
Create Date: 2025-06-12 13:50:46.876161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import peter_sslers

# revision identifiers, used by Alembic.
revision: str = '0c3414079bfe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limited',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp_created', peter_sslers.model.utils.TZDateTime(timezone=True), nullable=False),
    sa.Column('acme_server_id', sa.Integer(), nullable=False),
    sa.Column('acme_account_id', sa.Integer(), nullable=True),
    sa.Column('acme_order_id', sa.Integer(), nullable=True),
    sa.Column('server_response_body', sa.Text(), nullable=True),
    sa.Column('server_response_headers', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['acme_account_id'], ['acme_account.id'], ),
    sa.ForeignKeyConstraint(['acme_order_id'], ['acme_order.id'], ),
    sa.ForeignKeyConstraint(['acme_server_id'], ['acme_server.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('migrations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('migrations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp_migrated', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('rate_limited')
    # ### end Alembic commands ###
