"""index_acme_authorizaton_potential

Revision ID: 308c8116cb36
Revises: d17010e3d5a6
Create Date: 2025-10-13 14:40:25.051688

"""

from typing import Sequence, Union

from alembic import op


# edited template

# revision identifiers, used by Alembic.
revision: str = "308c8116cb36"
down_revision: Union[str, Sequence[str], None] = "d17010e3d5a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("acme_authorization_potential", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("uidx_acme_authorization_potential"))
        batch_op.create_index(
            batch_op.f("uidx_acme_authorization_potential"),
            [
                "acme_order_id",
                "domain_id",
                "acme_challenge_type_id",
            ],
            unique=True,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    pass
