"""reconciliation

Revision ID: 5bfca3b856ff
Revises: 5d517cf4d691
Create Date: 2025-08-28 11:10:53.179687

"""

from typing import Sequence, Union

from alembic import op

# import sqlalchemy as sa


# edited template
# import peter_sslers


# revision identifiers, used by Alembic.
revision: str = "5bfca3b856ff"
down_revision: Union[str, Sequence[str], None] = "5d517cf4d691"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table(
        "certificate_ca_reconciliation", "x509_certificate_trust_reconciliation"
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # --
    op.rename_table(
        "x509_certificate_trust_reconciliation", "certificate_ca_reconciliation"
    )
    # ### end Alembic commands ###
