"""reconciliation

Revision ID: 5bfca3b856ff
Revises: 5d517cf4d691
Create Date: 2025-08-28 11:10:53.179687

"""

from typing import Sequence, Union

from alembic import op

# import sqlalchemy as sa


# edited template
# import peter_sslers


# revision identifiers, used by Alembic.
revision: str = "5bfca3b856ff"
down_revision: Union[str, Sequence[str], None] = "5d517cf4d691"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table(
        "certificate_ca_reconciliation", "x509_certificate_trust_reconciliation"
    )
    with op.batch_alter_table("x509_certificate_trust_chain", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("uq_certificate_ca_chain_chain_pem"), type_="unique"
        )
        batch_op.drop_constraint(
            batch_op.f("uq_certificate_ca_chain_chain_pem_md5"), type_="unique"
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_x509_certificate_trust_chain_chain_pem"), ["chain_pem"]
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_x509_certificate_trust_chain_chain_pem_md5"),
            ["chain_pem_md5"],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("x509_certificate_trust_chain", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("uq_x509_certificate_trust_chain_chain_pem_md5"), type_="unique"
        )
        batch_op.drop_constraint(
            batch_op.f("uq_x509_certificate_trust_chain_chain_pem"), type_="unique"
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_certificate_ca_chain_chain_pem_md5"), ["chain_pem_md5"]
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_certificate_ca_chain_chain_pem"), ["chain_pem"]
        )

    op.rename_table(
        "x509_certificate_trust_reconciliation", "certificate_ca_reconciliation"
    )
    # ### end Alembic commands ###
