"""certificate_ca_chain

Revision ID: 5d517cf4d691
Revises: f3f5a545b186
Create Date: 2025-08-28 02:05:07.078488

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# edited template
# import peter_sslers

# revision identifiers, used by Alembic.
revision: str = "5d517cf4d691"
down_revision: Union[str, Sequence[str], None] = "f3f5a545b186"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.rename_table("certificate_ca_chain", "x509_certificate_trust_chain")
    with op.batch_alter_table("x509_certificate_trust_chain", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("uq_certificate_ca_chain_chain_pem"), type_="unique"
        )
        batch_op.drop_constraint(
            batch_op.f("uq_certificate_ca_chain_chain_pem_md5"), type_="unique"
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_x509_certificate_trust_chain_chain_pem"), ["chain_pem"]
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_x509_certificate_trust_chain_chain_pem_md5"),
            ["chain_pem_md5"],
        )

    with op.batch_alter_table("operations_object_event", schema=None) as batch_op:
        batch_op.alter_column(
            "certificate_ca_chain_id",
            new_column_name="x509_certificate_trust_chain_id",
        )
        batch_op.drop_constraint("ck__operations_object_event__check1")
        batch_op.create_check_constraint(
            batch_op.f("ck__operations_object_event__check1"),
            sa.text(
                " ( "
                " CASE WHEN acme_account_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN acme_account_key_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN acme_dns_server_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN acme_order_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN acme_server_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN certificate_ca_id IS NOT NULL THEN 1 ELSE 0 END"
                " + "
                " CASE WHEN coverage_assurance_event_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN domain_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN enrollment_factory_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN private_key_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN renewal_configuration_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN unique_fqdn_set_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN uniquely_challenged_fqdn_set_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN x509_certificate_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN x509_certificate_request_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN x509_certificate_trust_chain_id IS NOT NULL THEN 1 ELSE 0 END"
                " ) = 1",
            ),
        )

    with op.batch_alter_table("x509_certificate_chain", schema=None) as batch_op:
        batch_op.alter_column(
            "certificate_ca_chain_id",
            new_column_name="x509_certificate_trust_chain_id",
        )

    with op.batch_alter_table(
        "x509_certificate_trust_preference_policy", schema=None
    ) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("uq_certificate_ca_preference_policy_name"), type_="unique"
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_x509_certificate_trust_preference_policy_name"), ["name"]
        )

    with op.batch_alter_table(
        "x509_certificate_trust_preference_policy_item", schema=None
    ) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("uq_certificate_ca_preference_certificate_ca_id"), type_="unique"
        )
        batch_op.drop_index(batch_op.f("uidx_certificate_ca_preference_a"))
        batch_op.drop_index(batch_op.f("uidx_certificate_ca_preference_b"))
        batch_op.create_index(
            "uidx_x509_certificate_trust_preference_policy_item_a",
            ["x509_certificate_trust_preference_policy_id", "slot_id"],
            unique=True,
        )
        batch_op.create_index(
            "uidx_x509_certificate_trust_preference_policy_item_b",
            ["x509_certificate_trust_preference_policy_id", "certificate_ca_id"],
            unique=True,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "x509_certificate_trust_preference_policy_item", schema=None
    ) as batch_op:
        batch_op.drop_index("uidx_x509_certificate_trust_preference_policy_item_a")
        batch_op.drop_index("uidx_x509_certificate_trust_preference_policy_item_b")
        batch_op.create_index(
            batch_op.f("uidx_certificate_ca_preference_b"),
            ["x509_certificate_trust_preference_policy_id", "certificate_ca_id"],
            unique=True,
        )
        batch_op.create_index(
            batch_op.f("uidx_certificate_ca_preference_a"),
            ["x509_certificate_trust_preference_policy_id", "slot_id"],
            unique=True,
        )

        # this is a bad constraint!
        batch_op.create_unique_constraint(
            batch_op.f("uq_certificate_ca_preference_certificate_ca_id"),
            ["certificate_ca_id"],
        )

    with op.batch_alter_table(
        "x509_certificate_trust_preference_policy", schema=None
    ) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("uq_x509_certificate_trust_preference_policy_name"),
            type_="unique",
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_certificate_ca_preference_policy_name"), ["name"]
        )

    with op.batch_alter_table("x509_certificate_chain", schema=None) as batch_op:
        batch_op.alter_column(
            "x509_certificate_trust_chain_id",
            new_column_name="certificate_ca_chain_id",
        )

    with op.batch_alter_table("operations_object_event", schema=None) as batch_op:
        batch_op.alter_column(
            "x509_certificate_trust_chain_id",
            new_column_name="certificate_ca_chain_id",
        )
        batch_op.drop_constraint("ck__operations_object_event__check1")
        batch_op.create_check_constraint(
            batch_op.f("ck__operations_object_event__check1"),
            sa.text(
                " ( "
                " CASE WHEN acme_account_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN acme_account_key_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN acme_dns_server_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN acme_order_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN acme_server_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN certificate_ca_id IS NOT NULL THEN 1 ELSE 0 END"
                " + "
                " CASE WHEN certificate_ca_chain_id IS NOT NULL THEN 1 ELSE 0 END"
                " + "
                " CASE WHEN coverage_assurance_event_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN domain_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN enrollment_factory_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN private_key_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN renewal_configuration_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN unique_fqdn_set_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN uniquely_challenged_fqdn_set_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN x509_certificate_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN x509_certificate_request_id IS NOT NULL THEN 1 ELSE 0 END "
                " ) = 1",
            ),
        )

    op.rename_table("x509_certificate_trust_chain", "certificate_ca_chain")
    with op.batch_alter_table("certificate_ca_chain", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("uq_x509_certificate_trust_chain_chain_pem_md5"), type_="unique"
        )
        batch_op.drop_constraint(
            batch_op.f("uq_x509_certificate_trust_chain_chain_pem"), type_="unique"
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_certificate_ca_chain_chain_pem_md5"), ["chain_pem_md5"]
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_certificate_ca_chain_chain_pem"), ["chain_pem"]
        )

    # ### end Alembic commands ###
