"""prefix_certifcate_signed

Revision ID: 723b8620b0f0
Revises: feae28cb6dc2
Create Date: 2025-08-23 11:58:14.837859

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# edited template
# import peter_sslers

# revision identifiers, used by Alembic.
revision: str = "723b8620b0f0"
down_revision: Union[str, Sequence[str], None] = "feae28cb6dc2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.rename_table("certificate_request", "x509_certificate_request")
    with op.batch_alter_table("x509_certificate_request", schema=None) as batch_op:
        batch_op.alter_column(
            "certificate_request_source_id",
            new_column_name="x509_certificate_request_source_id",
        )

    with op.batch_alter_table("acme_event_log", schema=None) as batch_op:
        batch_op.alter_column(
            "certificate_request_id", new_column_name="x509_certificate_request_id"
        )

    with op.batch_alter_table("acme_order", schema=None) as batch_op:
        batch_op.alter_column(
            "certificate_request_id", new_column_name="x509_certificate_request_id"
        )

    with op.batch_alter_table("certificate_signed", schema=None) as batch_op:
        batch_op.alter_column(
            "certificate_request_id", new_column_name="x509_certificate_request_id"
        )

    with op.batch_alter_table("operations_object_event", schema=None) as batch_op:
        batch_op.alter_column(
            "certificate_request_id", new_column_name="x509_certificate_request_id"
        )
        batch_op.drop_constraint("check1")
        batch_op.create_check_constraint(
            batch_op.f("ck__operations_object_event__check1"),
            sa.text(
                " ( "
                " CASE WHEN acme_account_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN acme_account_key_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN acme_dns_server_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN acme_order_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN acme_server_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN certificate_ca_id IS NOT NULL THEN 1 ELSE 0 END"
                " + "
                " CASE WHEN certificate_ca_chain_id IS NOT NULL THEN 1 ELSE 0 END"
                " + "
                " CASE WHEN certificate_signed_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN coverage_assurance_event_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN domain_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN enrollment_factory_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN private_key_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN renewal_configuration_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN unique_fqdn_set_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN uniquely_challenged_fqdn_set_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN x509_certificate_request_id IS NOT NULL THEN 1 ELSE 0 END "
                " ) = 1",
            ),
        )

    with op.batch_alter_table("private_key", schema=None) as batch_op:
        batch_op.alter_column(
            "timestamp_last_certificate_request",
            new_column_name="timestamp_last_x509_certificate_request",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("private_key", schema=None) as batch_op:
        batch_op.alter_column(
            "timestamp_last_x509_certificate_request",
            new_column_name="timestamp_last_certificate_request",
        )

    with op.batch_alter_table("operations_object_event", schema=None) as batch_op:
        batch_op.alter_column(
            "x509_certificate_request_id", new_column_name="certificate_request_id"
        )

        batch_op.drop_constraint("ck__operations_object_event__check1")
        batch_op.create_check_constraint(
            batch_op.f("check1"),
            sa.text(
                " ( "
                " CASE WHEN acme_account_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN acme_account_key_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN acme_dns_server_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN acme_order_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN acme_server_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN certificate_ca_id IS NOT NULL THEN 1 ELSE 0 END"
                " + "
                " CASE WHEN certificate_ca_chain_id IS NOT NULL THEN 1 ELSE 0 END"
                " + "
                " CASE WHEN certificate_request_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN certificate_signed_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN coverage_assurance_event_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN domain_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN enrollment_factory_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN private_key_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN renewal_configuration_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN unique_fqdn_set_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN uniquely_challenged_fqdn_set_id IS NOT NULL THEN 1 ELSE 0 END "
                " ) = 1"
            ),
        )

    with op.batch_alter_table("certificate_signed", schema=None) as batch_op:
        batch_op.alter_column(
            "x509_certificate_request_id", new_column_name="certificate_request_id"
        )

    with op.batch_alter_table("acme_order", schema=None) as batch_op:
        batch_op.alter_column(
            "x509_certificate_request_id", new_column_name="certificate_request_id"
        )

    with op.batch_alter_table("acme_event_log", schema=None) as batch_op:
        batch_op.alter_column(
            "x509_certificate_request_id", new_column_name="certificate_request_id"
        )

    with op.batch_alter_table("x509_certificate_request", schema=None) as batch_op:
        batch_op.alter_column(
            "x509_certificate_request_source_id",
            new_column_name="certificate_request_source_id",
        )
    op.rename_table("x509_certificate_request", "certificate_request")

    # ### end Alembic commands ###
