"""fix_constraints

Revision ID: 83d46ba9e38f
Revises: c6365a020277
Create Date: 2025-08-28 15:22:54.086542

"""

from typing import Sequence, Union

from alembic import op

# import sqlalchemy as sa


# edited template
# import peter_sslers

# revision identifiers, used by Alembic.
revision: str = "83d46ba9e38f"
down_revision: Union[str, Sequence[str], None] = "c6365a020277"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("acme_authorization_potential", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("acme_authorization_potential_uidx"), type_="unique"
        )
        batch_op.create_index(
            "uidx_acme_authorization_potential",
            ["acme_order_id", "domain_id"],
            unique=True,
        )

    with op.batch_alter_table("acme_dns_server_account", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("domain_active_account"), type_="unique")
        batch_op.create_index(
            "uidx_domain_active_account",
            ["acme_dns_server_id", "domain_id", "is_active"],
            unique=True,
        )

    with op.batch_alter_table("x509_certificate_trusted", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("uq_certificate_ca_cert_pem"), type_="unique"
        )
        batch_op.drop_constraint(
            batch_op.f("uq_certificate_ca_cert_pem_md5"), type_="unique"
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_x509_certificate_trusted_cert_pem"), ["cert_pem"]
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_x509_certificate_trusted_cert_pem_md5"), ["cert_pem_md5"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("x509_certificate_trusted", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("uq_x509_certificate_trusted_cert_pem_md5"), type_="unique"
        )
        batch_op.drop_constraint(
            batch_op.f("uq_x509_certificate_trusted_cert_pem"), type_="unique"
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_certificate_ca_cert_pem_md5"), ["cert_pem_md5"]
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_certificate_ca_cert_pem"), ["cert_pem"]
        )

    with op.batch_alter_table("acme_dns_server_account", schema=None) as batch_op:
        batch_op.drop_index("uidx_domain_active_account")
        batch_op.create_unique_constraint(
            batch_op.f("domain_active_account"),
            ["acme_dns_server_id", "domain_id", "is_active"],
        )

    with op.batch_alter_table("acme_authorization_potential", schema=None) as batch_op:
        batch_op.drop_index("uidx_acme_authorization_potential")
        batch_op.create_unique_constraint(
            batch_op.f("acme_authorization_potential_uidx"),
            ["acme_order_id", "domain_id"],
        )

    # ### end Alembic commands ###
