"""certificate_ca

Revision ID: c6365a020277
Revises: 5bfca3b856ff
Create Date: 2025-08-28 11:56:10.052392

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# edited template
# import peter_sslers

# revision identifiers, used by Alembic.
revision: str = "c6365a020277"
down_revision: Union[str, Sequence[str], None] = "5bfca3b856ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.rename_table("certificate_ca", "x509_certificate_trusted")
    with op.batch_alter_table("x509_certificate_trusted", schema=None) as batch_op:
        batch_op.alter_column(
            "cert_issuer__certificate_ca_id",
            new_column_name="cert_issuer__x509_certificate_trusted_id",
        )
        batch_op.alter_column(
            "signed_by__certificate_ca_id",
            new_column_name="signed_by__x509_certificate_trusted_id",
        )
        batch_op.alter_column(
            "cross_signed_by__certificate_ca_id",
            new_column_name="cross_signed_by__x509_certificate_trusted_id",
        )

    op.rename_table(
        "root_store_version_2_certificate_ca",
        "root_store_version_2_x509_certificate_trusted",
    )
    with op.batch_alter_table(
        "root_store_version_2_x509_certificate_trusted", schema=None
    ) as batch_op:
        batch_op.alter_column(
            "certificate_ca_id",
            new_column_name="x509_certificate_trusted_id",
        )

    with op.batch_alter_table("operations_object_event", schema=None) as batch_op:
        batch_op.alter_column(
            "certificate_ca_id",
            new_column_name="x509_certificate_trusted_id",
        )
        batch_op.drop_constraint("ck__operations_object_event__check1")
        batch_op.create_check_constraint(
            batch_op.f("ck__operations_object_event__check1"),
            sa.text(
                " ( "
                " CASE WHEN acme_account_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN acme_account_key_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN acme_dns_server_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN acme_order_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN acme_server_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN coverage_assurance_event_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN domain_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN enrollment_factory_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN private_key_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN renewal_configuration_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN unique_fqdn_set_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN uniquely_challenged_fqdn_set_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN x509_certificate_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN x509_certificate_request_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN x509_certificate_trusted_id IS NOT NULL THEN 1 ELSE 0 END"
                " + "
                " CASE WHEN x509_certificate_trust_chain_id IS NOT NULL THEN 1 ELSE 0 END"
                " ) = 1",
            ),
        )

    with op.batch_alter_table("x509_certificate_trust_chain", schema=None) as batch_op:
        batch_op.alter_column(
            "certificate_ca_0_id",
            new_column_name="x509_certificate_trusted_0_id",
        )
        batch_op.alter_column(
            "certificate_ca_n_id",
            new_column_name="x509_certificate_trusted_n_id",
        )
        batch_op.alter_column(
            "certificate_ca_ids_string",
            new_column_name="x509_certificate_trusted_ids_string",
        )

    with op.batch_alter_table(
        "x509_certificate_trust_preference_policy_item", schema=None
    ) as batch_op:
        batch_op.alter_column(
            "certificate_ca_id",
            new_column_name="x509_certificate_trusted_id",
        )

    with op.batch_alter_table(
        "x509_certificate_trust_preference_policy_item", schema=None
    ) as batch_op:
        batch_op.drop_index(
            batch_op.f("uidx_x509_certificate_trust_preference_policy_item_a")
        )
        batch_op.drop_index(
            batch_op.f("uidx_x509_certificate_trust_preference_policy_item_b")
        )
        batch_op.create_index(
            batch_op.f("uidx_x509_certificate_trust_preference_policy_item_a"),
            ["x509_certificate_trust_preference_policy_id", "slot_id"],
            unique=True,
        )
        batch_op.create_index(
            batch_op.f("uidx_x509_certificate_trust_preference_policy_item_b"),
            [
                "x509_certificate_trust_preference_policy_id",
                "x509_certificate_trusted_id",
            ],
            unique=True,
        )

    with op.batch_alter_table(
        "x509_certificate_trust_reconciliation", schema=None
    ) as batch_op:
        batch_op.alter_column(
            "certificate_ca_id",
            new_column_name="x509_certificate_trusted_id",
        )
        batch_op.alter_column(
            "certificate_ca_id__issuer__reconciled",
            new_column_name="x509_certificate_trusted_id__issuer__reconciled",
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "x509_certificate_trust_reconciliation", schema=None
    ) as batch_op:
        batch_op.alter_column(
            "x509_certificate_trusted_id",
            new_column_name="certificate_ca_id",
        )
        batch_op.alter_column(
            "x509_certificate_trusted_id__issuer__reconciled",
            new_column_name="certificate_ca_id__issuer__reconciled",
        )

    with op.batch_alter_table(
        "x509_certificate_trust_preference_policy_item", schema=None
    ) as batch_op:
        batch_op.alter_column(
            "x509_certificate_trusted_id",
            new_column_name="certificate_ca_id",
        )

    with op.batch_alter_table(
        "x509_certificate_trust_preference_policy_item", schema=None
    ) as batch_op:
        batch_op.drop_index(
            batch_op.f("uidx_x509_certificate_trust_preference_policy_item_a")
        )
        batch_op.drop_index(
            batch_op.f("uidx_x509_certificate_trust_preference_policy_item_b")
        )
        batch_op.create_index(
            batch_op.f("uidx_x509_certificate_trust_preference_policy_item_a"),
            ["x509_certificate_trust_preference_policy_id", "slot_id"],
            unique=True,
        )
        batch_op.create_index(
            batch_op.f("uidx_x509_certificate_trust_preference_policy_item_b"),
            ["x509_certificate_trust_preference_policy_id", "certificate_ca_id"],
            unique=True,
        )

    with op.batch_alter_table("x509_certificate_trust_chain", schema=None) as batch_op:
        batch_op.alter_column(
            "x509_certificate_trusted_0_id",
            new_column_name="certificate_ca_0_id",
        )
        batch_op.alter_column(
            "x509_certificate_trusted_n_id",
            new_column_name="certificate_ca_n_id",
        )
        batch_op.alter_column(
            "x509_certificate_trusted_ids_string",
            new_column_name="certificate_ca_ids_string",
        )

    with op.batch_alter_table("operations_object_event", schema=None) as batch_op:
        batch_op.alter_column(
            "x509_certificate_trusted_id",
            new_column_name="certificate_ca_id",
        )
        batch_op.drop_constraint("ck__operations_object_event__check1")
        batch_op.create_check_constraint(
            batch_op.f("ck__operations_object_event__check1"),
            sa.text(
                " ( "
                " CASE WHEN acme_account_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN acme_account_key_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN acme_dns_server_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN acme_order_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN acme_server_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN certificate_ca_id IS NOT NULL THEN 1 ELSE 0 END"
                " + "
                " CASE WHEN coverage_assurance_event_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN domain_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN enrollment_factory_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN private_key_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN renewal_configuration_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN unique_fqdn_set_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN uniquely_challenged_fqdn_set_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN x509_certificate_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN x509_certificate_request_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN x509_certificate_trust_chain_id IS NOT NULL THEN 1 ELSE 0 END"
                " ) = 1",
            ),
        )

    op.rename_table(
        "root_store_version_2_x509_certificate_trusted",
        "root_store_version_2_certificate_ca",
    )
    with op.batch_alter_table(
        "root_store_version_2_certificate_ca", schema=None
    ) as batch_op:
        batch_op.alter_column(
            "x509_certificate_trusted_id",
            new_column_name="certificate_ca_id",
        )

    op.rename_table("x509_certificate_trusted", "certificate_ca")
    with op.batch_alter_table("certificate_ca", schema=None) as batch_op:
        batch_op.alter_column(
            "cert_issuer__x509_certificate_trusted_id",
            new_column_name="cert_issuer__certificate_ca_id",
        )
        batch_op.alter_column(
            "signed_by__x509_certificate_trusted_id",
            new_column_name="signed_by__certificate_ca_id",
        )
        batch_op.alter_column(
            "cross_signed_by__x509_certificate_trusted_id",
            new_column_name="cross_signed_by__certificate_ca_id",
        )
    # ### end Alembic commands ###
