"""prefix_certificate_signed

Revision ID: c83b22aa7aa3
Revises: 723b8620b0f0
Create Date: 2025-08-23 19:56:32.679809

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# edited template
# import peter_sslers

# revision identifiers, used by Alembic.
revision: str = "c83b22aa7aa3"
down_revision: Union[str, Sequence[str], None] = "723b8620b0f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.rename_table("certificate_signed", "x509_certificate")
    with op.batch_alter_table("x509_certificate", schema=None) as batch_op:
        batch_op.alter_column(
            "certificate_signed_id__replaces",
            new_column_name="x509_certificate_id__replaces",
        )
        batch_op.alter_column(
            "certificate_signed_id__replaced_by",
            new_column_name="x509_certificate_id__replaced_by",
        )

        batch_op.drop_constraint(
            batch_op.f("uq_certificate_signed_cert_pem"), type_="unique"
        )
        batch_op.drop_constraint(
            batch_op.f("uq_certificate_signed_cert_pem_md5"), type_="unique"
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_x509_certificate_cert_pem"), ["cert_pem"]
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_x509_certificate_cert_pem_md5"), ["cert_pem_md5"]
        )

    op.rename_table("certificate_signed_chain", "x509_certificate_chain")
    with op.batch_alter_table("x509_certificate_chain", schema=None) as batch_op:
        batch_op.alter_column(
            "certificate_signed_id",
            new_column_name="x509_certificate_id",
        )

    with op.batch_alter_table("acme_account", schema=None) as batch_op:
        batch_op.alter_column(
            "count_certificate_signeds",
            new_column_name="count_x509_certificates",
        )
        batch_op.alter_column(
            "timestamp_last_certificate_request",
            new_column_name="timestamp_last_x509_certificate_request",
        )

    with op.batch_alter_table("acme_event_log", schema=None) as batch_op:
        batch_op.alter_column(
            "certificate_signed_id",
            new_column_name="x509_certificate_id",
        )

    with op.batch_alter_table("acme_order", schema=None) as batch_op:
        batch_op.alter_column(
            "certificate_signed_id",
            new_column_name="x509_certificate_id",
        )
        batch_op.alter_column(
            "certificate_signed_id__replaces",
            new_column_name="x509_certificate_id__replaces",
        )

    with op.batch_alter_table("ari_check", schema=None) as batch_op:
        batch_op.alter_column(
            "certificate_signed_id",
            new_column_name="x509_certificate_id",
        )

    with op.batch_alter_table("coverage_assurance_event", schema=None) as batch_op:
        batch_op.alter_column(
            "certificate_signed_id",
            new_column_name="x509_certificate_id",
        )
        batch_op.drop_constraint("check_pkey_andor_certs")
        batch_op.create_check_constraint(
            batch_op.f("ck__coverage_assurance_event__check_pkey_andor_certs"),
            sa.text("(private_key_id IS NOT NULL OR x509_certificate_id IS NOT NULL)"),
        )

    with op.batch_alter_table("domain", schema=None) as batch_op:
        batch_op.alter_column(
            "certificate_signed_id__latest_single",
            new_column_name="x509_certificate_id__latest_single",
        )
        batch_op.alter_column(
            "certificate_signed_id__latest_multi",
            new_column_name="x509_certificate_id__latest_multi",
        )

    with op.batch_alter_table("operations_object_event", schema=None) as batch_op:
        batch_op.alter_column(
            "certificate_signed_id",
            new_column_name="x509_certificate_id",
        )
        batch_op.drop_constraint("ck__operations_object_event__check1")
        batch_op.create_check_constraint(
            batch_op.f("ck__operations_object_event__check1"),
            sa.text(
                " ( "
                " CASE WHEN acme_account_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN acme_account_key_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN acme_dns_server_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN acme_order_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN acme_server_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN certificate_ca_id IS NOT NULL THEN 1 ELSE 0 END"
                " + "
                " CASE WHEN certificate_ca_chain_id IS NOT NULL THEN 1 ELSE 0 END"
                " + "
                " CASE WHEN coverage_assurance_event_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN domain_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN enrollment_factory_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN private_key_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN renewal_configuration_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN unique_fqdn_set_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN uniquely_challenged_fqdn_set_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN x509_certificate_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN x509_certificate_request_id IS NOT NULL THEN 1 ELSE 0 END "
                " ) = 1",
            ),
        )

    with op.batch_alter_table("private_key", schema=None) as batch_op:
        batch_op.alter_column(
            "count_certificate_signeds",
            new_column_name="count_x509_certificates",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("private_key", schema=None) as batch_op:
        batch_op.alter_column(
            "count_x509_certificates",
            new_column_name="count_certificate_signeds",
        )

    with op.batch_alter_table("operations_object_event", schema=None) as batch_op:
        batch_op.alter_column(
            "x509_certificate_id",
            new_column_name="certificate_signed_id",
        )
        batch_op.drop_constraint("ck__operations_object_event__check1")
        batch_op.create_check_constraint(
            batch_op.f("ck__operations_object_event__check1"),
            sa.text(
                " ( "
                " CASE WHEN acme_account_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN acme_account_key_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN acme_dns_server_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN acme_order_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN acme_server_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN certificate_ca_id IS NOT NULL THEN 1 ELSE 0 END"
                " + "
                " CASE WHEN certificate_ca_chain_id IS NOT NULL THEN 1 ELSE 0 END"
                " + "
                " CASE WHEN certificate_signed_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN coverage_assurance_event_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN domain_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN enrollment_factory_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN private_key_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN renewal_configuration_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN unique_fqdn_set_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN uniquely_challenged_fqdn_set_id IS NOT NULL THEN 1 ELSE 0 END "
                " + "
                " CASE WHEN x509_certificate_request_id IS NOT NULL THEN 1 ELSE 0 END "
                " ) = 1",
            ),
        )

    with op.batch_alter_table("domain", schema=None) as batch_op:
        batch_op.alter_column(
            "x509_certificate_id__latest_single",
            new_column_name="certificate_signed_id__latest_single",
        )
        batch_op.alter_column(
            "x509_certificate_id__latest_multi",
            new_column_name="certificate_signed_id__latest_multi",
        )

    with op.batch_alter_table("coverage_assurance_event", schema=None) as batch_op:
        batch_op.alter_column(
            "x509_certificate_id",
            new_column_name="certificate_signed_id",
        )
        batch_op.drop_constraint("ck__coverage_assurance_event__check_pkey_andor_certs")
        batch_op.create_check_constraint(
            batch_op.f("check_pkey_andor_certs"),
            sa.text(
                "(private_key_id IS NOT NULL OR certificate_signed_id IS NOT NULL)"
            ),
        )

    with op.batch_alter_table("ari_check", schema=None) as batch_op:
        batch_op.alter_column(
            "x509_certificate_id",
            new_column_name="certificate_signed_id",
        )

    with op.batch_alter_table("acme_order", schema=None) as batch_op:
        batch_op.alter_column(
            "x509_certificate_id",
            new_column_name="certificate_signed_id",
        )
        batch_op.alter_column(
            "x509_certificate_id__replaces",
            new_column_name="certificate_signed_id__replaces",
        )

    with op.batch_alter_table("acme_event_log", schema=None) as batch_op:
        batch_op.alter_column(
            "x509_certificate_id",
            new_column_name="certificate_signed_id",
        )

    with op.batch_alter_table("acme_account", schema=None) as batch_op:
        batch_op.alter_column(
            "count_x509_certificates",
            new_column_name="count_certificate_signeds",
        )
        batch_op.alter_column(
            "timestamp_last_x509_certificate_request",
            new_column_name="timestamp_last_certificate_request",
        )

    op.rename_table("x509_certificate_chain", "certificate_signed_chain")
    with op.batch_alter_table("certificate_signed_chain", schema=None) as batch_op:
        batch_op.alter_column(
            "x509_certificate_id",
            new_column_name="certificate_signed_id",
        )

    op.rename_table("x509_certificate", "certificate_signed")
    with op.batch_alter_table("certificate_signed", schema=None) as batch_op:
        batch_op.alter_column(
            "x509_certificate_id__replaces",
            new_column_name="certificate_signed_id__replaces",
        )
        batch_op.alter_column(
            "x509_certificate_id__replaced_by",
            new_column_name="certificate_signed_id__replaced_by",
        )

        batch_op.drop_constraint(
            batch_op.f("uq_x509_certificate_cert_pem_md5"), type_="unique"
        )
        batch_op.drop_constraint(
            batch_op.f("uq_x509_certificate_cert_pem"), type_="unique"
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_certificate_signed_cert_pem_md5"), ["cert_pem_md5"]
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_certificate_signed_cert_pem"), ["cert_pem"]
        )
