"""certificate_ca_preference_policy

Revision ID: f3f5a545b186
Revises: 0e61098c8fde
Create Date: 2025-08-28 01:47:43.762880

"""

from typing import Sequence, Union

from alembic import op

# import sqlalchemy as sa


# edited template
# import peter_sslers

# revision identifiers, used by Alembic.
revision: str = "f3f5a545b186"
down_revision: Union[str, Sequence[str], None] = "0e61098c8fde"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table(
        "certificate_ca_preference_policy", "x509_certificate_trust_preference_policy"
    )
    op.rename_table(
        "certificate_ca_preference", "x509_certificate_trust_preference_policy_item"
    )
    with op.batch_alter_table(
        "x509_certificate_trust_preference_policy_item", schema=None
    ) as batch_op:
        batch_op.alter_column(
            "certificate_ca_preference_policy_id",
            new_column_name="x509_certificate_trust_preference_policy_id",
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.rename_table(
        "x509_certificate_trust_preference_policy_item", "certificate_ca_preference"
    )
    with op.batch_alter_table("certificate_ca_preference", schema=None) as batch_op:
        batch_op.alter_column(
            "x509_certificate_trust_preference_policy_id",
            new_column_name="certificate_ca_preference_policy_id",
        )
    op.rename_table(
        "x509_certificate_trust_preference_policy", "certificate_ca_preference_policy"
    )
    # ### end Alembic commands ###
