# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup Hosts
      run: |
        sudo cat peter_sslers/tests/test_data/hosts.txt | sudo tee -a /etc/hosts
    - name: Install core Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade tox setuptools flake8 pytest
        pip list
    - name: Install Redis
      run: |
        sudo apt-get install redis
    - name: Install Pebble
      run: |
        export GOPATH=$HOME/go
        go get -u github.com/letsencrypt/pebble/...
        cd $GOPATH/src/github.com/letsencrypt/pebble && go install ./...
    - name: Test with pytest
      ports:
        - 80:80
        - 5002:5002
        - 7201:7201
      run: |
        export SSL_RUN_REDIS_TESTS=1
        export SSL_BIN_REDIS_SERVER=/usr/bin/redis-server
        export SSL_RUN_API_TESTS__PEBBLE=1
        export GOPATH=$HOME/go
        export PATH=$GOPATH/bin:$PATH
        tox -e py -- ${{ matrix.pytest-args }}
