# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        # python-version: [2.7, 3.8]
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install core Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade tox setuptools flake8 pytest
        pip list
    - name: Setup Hosts
      # several tests require custom domains to point back to 127.0.0.1
      run: |
        sudo cat tests/test_configuration/hosts.txt | sudo tee -a /etc/hosts
    - name: Install Redis
      # several tests require Redis
      # note: if tests hang, it could be because the Redis version has changed
      run: |
        sudo apt-get install redis
        # /var/lib/redis/peter_sslers_test is listed in the test redis-server.conf
        sudo mkdir -p /var/lib/redis/peter_sslers_test
        sudo chown -R runner /var/lib/redis/peter_sslers_test
        sudo chown -R runner /var/lib/redis
    - name: Install Pebble
      # several tests require a Pebble instance (ACME Server)
      run: |
        export GOPATH=$HOME/go
        go get -u github.com/letsencrypt/pebble/...
        cd $GOPATH/src/github.com/letsencrypt/pebble && go install ./...
    - name: Install OpenResty
      # several tests require an OpenResty server
      run: |
        # install OpenResty
        sudo apt-get -y install --no-install-recommends wget gnupg ca-certificates
        wget -O - https://openresty.org/package/pubkey.gpg | sudo apt-key add -
        echo "deb http://openresty.org/package/ubuntu $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/openresty.list
        sudo apt-get update
        sudo apt-get -y install openresty
        # install PeterSSlers
        sudo /usr/local/openresty/bin/opm get aptise/peter_sslers-lua-resty
        # list some config info
        sudo ls -alh /etc/openresty
        sudo ls -alh /usr/local/openresty/nginx
    - name: Test with tox/pytest
      # tox is used to run pytest
      run: |
        export SSL_RUN_REDIS_TESTS=1
        export SSL_BIN_REDIS_SERVER=/usr/bin/redis-server
        export SSL_RUN_API_TESTS__PEBBLE=1
        export GOPATH=$HOME/go
        export PATH=$GOPATH/bin:$PATH
        tox -e py -- ${{ matrix.pytest-args }}
